set_property SRC_FILE_INFO {cfile:D:/Pogramas/practica3/practica3.srcs/constrs_1/imports/practica3/Basys3_Master.xdc rfile:../../../practica3.srcs/constrs_1/imports/practica3/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks{sys_clk_pin}] -min-add_delay 0.70 [get_ports{X[0]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks{sys_clk_pin}] -max-add_delay 1.75 [get_ports{X[0]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay-clock [get_clocks{sys_clk_pin}] -min -add_delay 0.70 [get_ports{X[1]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay-clock [get_clocks{sys_clk_pin}] -max -add_delay 1.75 [get_ports{X[1]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks{sys_clk_pin}] -min -add_delay 0.70 [get_ports{X[2]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks{sys_clk_pin}] -max -add_delay 1.75 [get_ports{X[2]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks{sys_clk_pin}] -min -add_delay 0.70 [get_ports{X[3]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks{sys_clk_pin}] -max -add_delay 1.75 [get_ports{X[3]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks{sys_clk_pin}] -min -add_delay 0.70 [get_ports{Y[0]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks{sys_clk_pin}] -max -add_delay 1.75 [get_ports{Y[0]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks{sys_clk_pin}] -min -add_delay 0.70 [get_ports{Y[1]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks{sys_clk_pin}] -max -add_delay 1.75 [get_ports{Y[1]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks{sys_clk_pin}] -min -add_delay 0.70 [get_ports{Y[2]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks{sys_clk_pin}] -max -add_delay 1.75 [get_ports{Y[2]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks{sys_clk_pin}] -min -add_delay 0.70 [get_ports{Y[3]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks{sys_clk_pin}] -max -add_delay 1.75 [get_ports{Y[3]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks{sys_clk_pin}] -min -add_delay 0.30 [get_ports{Z[0]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks{sys_clk_pin}] -max -add_delay 1.30 [get_ports{Z[0]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks{sys_clk_pin}] -min -add_delay 0.30 [get_ports{Z[1]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks{sys_clk_pin}] -max -add_delay 1.30 [get_ports{Z[1]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks{sys_clk_pin}] -min -add_delay 0.30 [get_ports{Z[2]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks{sys_clk_pin}] -max -add_delay 1.30 [get_ports{Z[2]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks{sys_clk_pin}] -min -add_delay 0.30 [get_ports{Z[3]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks{sys_clk_pin}] -max -add_delay 1.30 [get_ports{Z[3]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks{sys_clk_pin}] -min -add_delay 0.30 [get_ports{Z[4]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks{sys_clk_pin}] -max -add_delay 1.30 [get_ports{Z[4]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks{sys_clk_pin}] -min -add_delay 0.30 [get_ports{Z[5]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks{sys_clk_pin}] -max -add_delay 1.30 [get_ports{Z[5]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks{sys_clk_pin}] -min -add_delay 0.30 [get_ports{Z[6]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks{sys_clk_pin}] -max -add_delay 1.30 [get_ports{Z[6]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks{sys_clk_pin}] -min -add_delay 0.30 [get_ports{Z[7]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks{sys_clk_pin}] -max -add_delay 1.30 [get_ports{Z[7]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {X[0]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {X[1]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports {X[2]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W17 [get_ports {X[3]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W15 [get_ports {Y[0]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V15 [get_ports {Y[1]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W14 [get_ports {Y[2]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13 [get_ports {Y[3]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {Z[0]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports {Z[1]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U19 [get_ports {Z[2]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V19 [get_ports {Z[3]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W18 [get_ports {Z[4]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U15 [get_ports {Z[5]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14 [get_ports {Z[6]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V14 [get_ports {Z[7]}]
