# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Pogramas/practica5/practica5.cache/wt [current_project]
set_property parent.project_path D:/Pogramas/practica5/practica5.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo d:/Pogramas/practica5/practica5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Pogramas/practica5/practica5.srcs/sources_1/new/contador10.vhd
  D:/Pogramas/practica5/practica5.srcs/sources_1/imports/recursos/conv_7seg.vhd
  D:/Pogramas/practica5/practica5.srcs/sources_1/imports/recursos/debouncer.vhd
  D:/Pogramas/practica5/practica5.srcs/sources_1/imports/recursos/displays.vhd
  D:/Pogramas/practica5/practica5.srcs/sources_1/imports/recursos/divisor.vhd
  D:/Pogramas/practica5/practica5.srcs/sources_1/new/multiplexor.vhd
  D:/Pogramas/practica5/practica5.srcs/sources_1/new/tragaperras.vhd
  D:/Pogramas/practica5/practica5.srcs/sources_1/imports/recursos/sintesis_tragaperras.vhd
}
read_ip -quiet D:/Pogramas/practica5/practica5.srcs/sources_1/ip/memoria_bram/memoria_bram.xci
set_property used_in_implementation false [get_files -all d:/Pogramas/practica5/practica5.srcs/sources_1/ip/memoria_bram/memoria_bram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Pogramas/practica5/practica5.srcs/constrs_1/imports/recursos/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/Pogramas/practica5/practica5.srcs/constrs_1/imports/recursos/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top sintesis_tragaperras -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef sintesis_tragaperras.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file sintesis_tragaperras_utilization_synth.rpt -pb sintesis_tragaperras_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
